### ISSUE TITLE
Automatic module name?

### ISSUE THREAD

**Issue by mtdowling** [samskivert/jmustache#105]
Could you add an automatic module name to this library so that it can be used in a modular (Java 9+) application? As of right now, your module name is inferred as "jmustache" which is dangerous to rely on if, for example, when you do add an automatic module name your name differs from the inferred name.

http://branchandbound.net/blog/java/2017/12/automatic-module-name/

**Comment by samskivert** [comment]
Added in 8f7f2b228333c463c4bb049fd8b113fda7e1f411. Should go out in next release.
