### ISSUE TITLE
Release with Visitor mechanism

### ISSUE THREAD

**Issue by meirf** [samskivert/jmustache#109]
The Visitor mechanism, which [looks extremely useful](https://github.com/samskivert/jmustache/issues/108#issuecomment-510071602), was committed in https://github.com/samskivert/jmustache/commit/37e31cbeaceda1debb10743170dd6197ad6baa70 which is right after the 1.14 release. Is there a plan to release 1.15 so that the `Visitor` mechanism can be exposed?

**Comment by samskivert** [comment]
Release is out and should be headed to Maven Central soon.

**Comment by meirf** [comment]
That's awesome. Thank you. 

I don't yet see it here https://mvnrepository.com/artifact/com.samskivert/jmustache. Is there somewhere else I should look?
