### ISSUE TITLE
Variable Issues on Windows 10

### ISSUE THREAD

**Issue by mkshin96** [samskivert/jmustache#118]
I was implementing a login with OAuth2 using `Spring Boot2.1.x` and `jmustache1.14`.(Referenced https://github.com/jojoldu/freelec-springboot2-webservice) 
~~~java
@GetMapping("/")
public String index(Model model) {
    model.addAttribute("posts", postsService.findAllDesc());
    SessionUser user = (SessionUser) httpSession.getAttribute("user"); 
    if (user != null) {
        model.addAttribute("userName", user.getName());
    }
    return "index";
}
~~~

~~~mustache
<div class="row">
    <div class="col-md-6">
        <a href="/posts/save" role="button" class="btn btn-primary">글 등록</a>
        {{#userName}}
            Logged in as: <span id="user">{{userName}}</span>
            <a href="/logout" class="btn btn-info active" role="button">Logout</a>
        {{/userName}}
        {{^userName}}
            <a href="/oauth2/authorization/google" class="btn btn-success active" role="button">Google Login</a>
            <a href="/oauth2/authorization/naver" class="btn btn-secondary active" role="button">Naver Login</a>
        {{/userName}}
    </div>
</div>
~~~
I expected my name registered with Google would be bound(My name is 신무곤). But the result is
![image](https://user-images.githubusercontent.com/34432494/73999799-3b374500-49a9-11ea-974f-04493fce25fc.png)

In my opinion this seems to be a Windows variable bound. The reason is that
![image](https://user-images.githubusercontent.com/34432494/73999939-ada82500-49a9-11ea-9a29-b930d473b4f6.png)

How can I solve this? Thank you for reading!

**Comment by agentgt** [comment]
Sorry I'm fairly sure this is not a JMustache issue.

@samskivert I think we can close this issue.

It appears based on this comment it was resolved for them:

https://github.com/jojoldu/freelec-springboot2-webservice/issues/169#issuecomment-674488585
