### ISSUE TITLE
proguard related issue

### ISSUE THREAD

**Issue by xeoshow** [samskivert/jmustache#56]
Hi, 

I found in below code, I must keep the variable name "Object persons" unchanged after applied proguard, otherwise will cause error.

How could I create such settings in proguard file? Thanks for help!

String tmpl = "{{#persons}}{{name}}: {{age}}{{/persons}}\n";
Mustache.compiler().compile(tmpl).execute(new Object() {
    Object persons = Arrays.asList(new Person("Elvis", 75), new Person("Madonna", 52));
});

**Comment by hovi** [comment]
Just for the record - I had some trouble setting up proguard so posting my example config, the `{ *; }` what I missed:

```
-keep class yourpackage.of.context.classes.** { *; }
```
