### ISSUE TITLE
Jmustache is slow on android

### ISSUE THREAD

**Issue by atali** [samskivert/jmustache#58]
Hello Guys,

Is there any means to accelerate jmustache on Android ? It's very slow. Because of serialization I suppose ? Can we use parceable  or anything else to do the job ?

**Comment by martyglaubitz** [comment]
i think AOT compilation of the templates via the Java Preprocessor API would be a viable solution here

**Comment by samskivert** [comment]
I'm going to close this for now. If anyone else is having trouble with performance on Android, it would be useful to know more about your particular use case. Do you have especially large templates? Are you using deeply nested getters that have to make a lot of reflective calls to fetch the data that is used in your template?

I suspect that for moderately sized templates (like that may substitute in a few hundred values), performance should be fine, but I've never used JMustache on Android. So maybe reflection really is 10x slower than a hashmap lookup or something crazy that would be causing major performance problems.
