### ISSUE TITLE
How to deactivate unresolvable properties exception

### ISSUE THREAD

**Issue by dariodariodario** [samskivert/jmustache#71]
Hello,
I'm using jmustache within the spring boot plugin. If a put a field like {{field}} that is not in the model, I keep getting an exception. I've read your docs and I've tried to se compile.defaultValue(""), but I still keep getting it. Any idea on how to solve this... ?

**Comment by samskivert** [comment]
I would need to know what exception you are getting. `compile.defaultValue("")` should do what you are trying to do.

**Comment by dariodariodario** [comment]
This is the exception:
com.samskivert.mustache.MustacheException$Context: No method or field with name 'Title' on line 8

and this is the code

```Java
 public String renderView(String viewName, Map<String, Object> model) throws IOException {
        Template template = loadTemplate(viewName);
        return template.execute(model);
    }

    private Template loadTemplate(String viewName) throws IOException {
        URL url = classLoader.getResource("templates/" + viewName + ".html");
        long templateLastModified = url.openConnection().getLastModified();
        TemplateInfo templateInfo = templates.get(viewName);
        if (cache && templateInfo != null){
            if (templateLastModified >= templateInfo.getLastModified()){
                return templateInfo.getTemplate();
            }
        }

        InputStream inputStream = url.openStream();
        String viewTemplate = IOUtils.toString(inputStream);
        Template template = compiler
                .defaultValue("")
                .nullValue("")
                .compile(viewTemplate);

        templates.put(viewName, new TemplateInfo(template, templateLastModified));

        return template;
    }
```

**Comment by samskivert** [comment]
You must only call *either* `defaultValue` or `nullValue`. `defaultValue` means *always* use this value regardless of whether a field is missing or null. `nullValue` means only use this value if a field is null, fail if it is missing. Since you call `nullValue` last, that's the behavior that's being used. Remove the call to `nullValue` and it will work as you expect.
