### ISSUE TITLE
Support for Java 8 Optionals

### ISSUE THREAD

**Issue by testinfected** [samskivert/jmustache#72]
First things first, thanks a lot for JMustache. Love it!

It would be nice if Java 8 Optionals were supported so that `Optional.empty()` is treated as the `nullValue` and if `Optional.isPresent()` then consider the value to be `Optional.get()`.

What do you think?

**Comment by samskivert** [comment]
Yeah, that sounds great, but unfortunately if I add that then JMustache becomes incompatible with Java 6 and 7 which is really big price to pay.

I'll see if there's some way that Optional support can be added without making JMustache unusable by older JVMs.

**Comment by samskivert** [comment]
It looks like you can do it already with a custom `Collector`:

```java
    @Test public void testOptionalSupportingCollector () {
        Mustache.Compiler comp = Mustache.compiler().withCollector(new DefaultCollector() {
            public Iterator<?> toIterator (final Object value) {
                if (value instanceof Optional<?>) {
                    Optional<?> opt = (Optional<?>) value;
                    return opt.isPresent() ? Collections.singleton(opt.get()).iterator() :
                        Collections.emptyList().iterator();
                } else return super.toIterator(value);
            }
        });
        test(comp, "test", "{{#foo}}{{.}}{{/foo}}", context("foo", Optional.of("test")));
        test(comp, "", "{{#foo}}{{.}}{{/foo}}", context("foo", Optional.empty()));
        test(comp, "", "{{^foo}}{{.}}{{/foo}}", context("foo", Optional.of("test")));
        test(comp, "test", "{{^foo}}test{{/foo}}", context("foo", Optional.empty()));
    }
```

**Comment by samskivert** [comment]
There's another open issue which deals with supporting default methods on Java 8 interfaces, so maybe I will eventually create a Java8Collector() which can bundle both support for Optional and default interfaces in a way that does not break support for Java 6/7.

**Comment by samskivert** [comment]
Oh, I forgot I was able to fix that without using Java 8 specific APIs, so maybe a Java8Collector isn't particularly useful, but still it's pretty easy to roll your own, so that's probably a good solution for now.

**Comment by testinfected** [comment]
A custom `Collector` will do for now. Thanks!

I kinda like the idea of a `Java8Collector` which bundles Java 8 features. You could compile against 1.8 but still make the byte code 1.6 compatible. Anyone who uses the `Java8Collector` would obviously need Java 8, but Java 6/7 users who don't import it would be fine.

**Comment by testinfected** [comment]
On second thought that might work for `Optional`, but won't work for default methods. Well, forget it.
