### ISSUE TITLE
{{{var}}} to prevent html encoding now not works?

### ISSUE THREAD

**Issue by QianJin2013** [samskivert/jmustache#76]
When use 1.9, it was ok to using triple brackets {{{var}}} to prevent html encoding,
but 1.12 not works, it encode anyway
now 
"=" is encoded to "&#x3D;"
住所の種類 is encoded to \u4F4F\u6240\u306E\u7A2E\u985E

hope you check this at next release

**Comment by samskivert** [comment]
I can't reproduce this error. For example, this test passes:

```
    @Test public void testUnescapeHTML () {
        check("住所の種類", Mustache.compiler().escapeHTML(true).compile("{{{a}}}").
              execute(context("a", "住所の種類")));
    }
```

So it doesn't look like 住所の種類 is getting changed inside triple brackets. Can you provide me with a failing test?

**Comment by QianJin2013** [comment]
Thank you! I run your test case with my template, actually no problem.  I am sorry i must did wrong test way, sorry to bother you.
