### ISSUE TITLE
Question on delimiter

### ISSUE THREAD

**Issue by wing328** [samskivert/jmustache#78]
According to mustache doc, I can set the delimiter as follows:
```
* {{default_tags}}
{{=<% %>=}}
* <% erb_style_tags %>
<%={{ }}=%>
* {{ default_tags_again }}
```
Ref: https://mustache.github.io/mustache.5.html

After setting delimiter to <%, %>, how can I get the unescape value of the tag, which can be obtained from {{{ }}} before changing the delimiter?

I tried <%{ }%> and {<% %>} but no luck.

Trying to map {{{ and }}} to something else but no luck either.

**Comment by samskivert** [comment]
Presently, once you change tags, there's no way to access the triple-mustache form. I don't know if there's a "standard" approach to handling this in other Mustache implementations, if so I'm happy to implement it. I don't see anything in the spec/docs about this.

**Comment by samskivert** [comment]
However the & form should still work:

"You can also use & to unescape a variable: {{& name}}. This may be useful when changing delimiters (see "Set Delimiter" below)."

**Comment by wing328** [comment]
OK. I'll give {{& name}} a try. Thanks for the prompt response.

**Comment by wing328** [comment]
@samskivert confirmed that it works for me. Thanks for your help.
