### ISSUE TITLE
Opening <a> tag not recognized?

### ISSUE THREAD

**Issue by delenius** [samskivert/jmustache#83]
It seems that this does not work:

```
{{{<a href="https://www.promisejs.org/api/">Promise</a>}}}
```

I get an error saying that the closing `</a>` tag does not match whatever the previous opening tag is. The opening `<a>` tag is not recognized, I guess.

**Comment by yihtserns** [comment]
Is `<a href="https://www.promisejs.org/api/">Promise</a>` a variable name?

Why is it in `{{{...}}}`?

**Comment by delenius** [comment]
Hmm, the file I was working on was using <> as tags instead of {{ }}, but it was causing problems with literal HTML content. I switched to using {{ }} for this part, and avoided the problem.
