### ISSUE TITLE
Build fails with oraclejdk7 after upgrade to 1.14

### ISSUE THREAD

**Issue by Nadahar** [samskivert/jmustache#94]
I updated our version of jmustache from 1.13 to 1.14, which makes our Travis CI build fail on oraclejdk7 with:
```powershell
java.lang.UnsupportedClassVersionError: com/samskivert/mustache/MustacheException : Unsupported major.minor version 52.0
	at net.pms.logging.LoggingTest.testDebugLogPropertyDefiner(LoggingTest.java:159)
```

What's strange is that I can build using Java 7 on Windows, and it also builds on Linux using openjdk7.

I've had similar problems before, and it's usually caused by the build being made using a newer Java version and the targeting of 1.7 not working properly. I haven't researched it enough to really understand the cause, I've simply built the release using Java 7.

I'll just downgrade to 1.13 for now, but thought you'd like to know.

**Comment by samskivert** [comment]
Oops, this is no bug, just me being stupid. I updated everything to source level 1.8 at some point, not even thinking about 1.7 users. I reverted it to 1.7, so the next release should once again be 1.7 compatible.

**Comment by xiaoyihu** [comment]
Hello, my project is running on jre 1.6 and do you have any plan to support 1.6?

**Comment by samskivert** [comment]
Unfortunately not. JRE 1.6 is _extremely_ old. You could probably build the project yourself with JDK 1.6 and make whatever small changes you need to make it work, but I'm not going to burden the normal release with supporting a JRE version that was end-of-lifed five years ago.
